CREATE TABLE SHOPPING_LIST (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE ITEM (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    bought BOOLEAN,
    shopping_list_id BIGINT,
    FOREIGN KEY (shopping_list_id) REFERENCES SHOPPING_LIST(id)
);

